"""added profile_picture_url  column

Revision ID: 4b6404a4e2f8
Revises: c0c3f55f76d8
Create Date: 2025-06-07 18:53:24.604356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6404a4e2f8'
down_revision: Union[str, None] = 'c0c3f55f76d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
