"""add_sla_monitoring_tables

Revision ID: 47cf2e40fa2f
Revises: b9f1a99fa4b6
Create Date: 2025-06-19 17:13:16.953388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from infrastructure.db.models.user_model import GUID

# revision identifiers, used by Alembic.
revision: str = '47cf2e40fa2f'
down_revision: Union[str, None] = 'b9f1a99fa4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_metrics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('threshold_warning', sa.Float(), nullable=False),
    sa.Column('threshold_critical', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_metrics_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_metrics_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_metrics_status'), ['status'], unique=False)

    op.create_table('sla_reports',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=False),
    sa.Column('critical_metrics_count', sa.Integer(), nullable=False),
    sa.Column('warning_metrics_count', sa.Integer(), nullable=False),
    sa.Column('healthy_metrics_count', sa.Integer(), nullable=False),
    sa.Column('total_metrics_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_reports_overall_status'), ['overall_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_reports_report_type'), ['report_type'], unique=False)

    op.create_table('sla_thresholds',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('critical_threshold', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_type', 'is_active', name='_metric_type_active_uc')
    )
    with op.batch_alter_table('sla_thresholds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_thresholds_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_thresholds_metric_type'), ['metric_type'], unique=False)

    op.create_table('sla_alerts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', GUID(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_alerts_acknowledged'), ['acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_alerts_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_alerts_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_alerts_triggered_at'), ['triggered_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sla_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_alerts_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_sla_alerts_resolved'))
        batch_op.drop_index(batch_op.f('ix_sla_alerts_metric_type'))
        batch_op.drop_index(batch_op.f('ix_sla_alerts_alert_type'))
        batch_op.drop_index(batch_op.f('ix_sla_alerts_acknowledged'))

    op.drop_table('sla_alerts')
    with op.batch_alter_table('sla_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_thresholds_metric_type'))
        batch_op.drop_index(batch_op.f('ix_sla_thresholds_is_active'))

    op.drop_table('sla_thresholds')
    with op.batch_alter_table('sla_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_sla_reports_overall_status'))
        batch_op.drop_index(batch_op.f('ix_sla_reports_generated_at'))

    op.drop_table('sla_reports')
    with op.batch_alter_table('sla_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_metrics_status'))
        batch_op.drop_index(batch_op.f('ix_sla_metrics_metric_type'))
        batch_op.drop_index(batch_op.f('ix_sla_metrics_measured_at'))

    op.drop_table('sla_metrics')
    # ### end Alembic commands ###
